### ISSUE TITLE
Subversion fails "symbol(s) not found for architecture i386"

### ISSUE THREAD

**Issue by barryhippo** [Homebrew/homebrew#35811]
I used "brew install --universal --with-java subversion" to install javahl ,an error appeared.
Any help would be appreciated. Thanks.

wanghaodeMacBook-Pro:~ wanghao$ brew install --universal --with-jdk subversion
==> Downloading http://www.apache.org/dyn/closer.cgi?path=subversion/subversion-
==> Best Mirror http://mirrors.advancedhosters.com/apache/subversion/subversion-
######################################################################## 100.0%
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
==> Downloading https://serf.googlecode.com/svn/src_releases/serf-1.3.7.tar.bz2
######################################################################## 100.0%
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.8.10_2/
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion/1.8.10_2 --with-zlib=/usr 
==> make
      _check_watchdog in named_atomic-test-proc.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [subversion/tests/libsvn_subr/named_atomic-proc-test] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
Subversion fails install on Yosemite (https://github.com/Homebrew/homebrew/issues/35744)
Subversion fails on 10.10 --with-python (https://github.com/Homebrew/homebrew/issues/34119)

This is the debug logs:
https://gist.github.com/anonymous/e123c1dab2ca69e13a84

**Comment by jacknagel** [comment]
@DomT4 - looks like our apr needs needs a universal option.

**Comment by DomT4** [comment]
@jacknagel Working on it now.

**Comment by DomT4** [comment]
Should be fixed in #35827.

**Comment by barryhippo** [comment]
@DomT4 It means I needs to use "brew install --universal apr/apr-util" to install apr and apr-util?

**Comment by DomT4** [comment]
@barryhippo Once #35827 is merged, you should just be able to ` brew update && brew upgrade ` and then re-do ` brew install --universal --with-java subversion ` and it should pull in the universal dependencies automatically.

**Comment by jacknagel** [comment]
merged the fix.

**Comment by barryhippo** [comment]
This problem is still appeared.
But there have little different:
wanghaodeMacBook-Pro:~ wanghao$ brew install --universal --with-java subversion
==> Downloading http://www.apache.org/dyn/closer.cgi?path=subversion/subversion-
Already downloaded: /Library/Caches/Homebrew/subversion-1.8.10.tar.bz2
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
==> Downloading https://serf.googlecode.com/svn/src_releases/serf-1.3.7.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion--serf-1.3.7.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.8.10_2/
==> /usr/local/opt/scons/bin/scons install
Warning: JAVA_HOME is set. Try unsetting it if JNI headers cannot be found.
==> ./configure --prefix=/usr/local/Cellar/subversion/1.8.10_2 --with-zlib=/usr 
==> make
-------here is different:
  "_apr_time_now", referenced from:
      _print_dirent in list-cmd.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [subversion/svn/svn] Error 1

the debug logs:
https://gist.github.com/1c2b0ee1a0bfc89c36bb

**Comment by DomT4** [comment]
Blurgh. That's frustrating. Does ` brew install apr --universal ` work for you outside of ` subversion `?

**Comment by barryhippo** [comment]
That's amazing,thanks @DomT4.

**Comment by DomT4** [comment]
Did it work outside the ` subversion ` install?

**Comment by barryhippo** [comment]
Yes,I use "brew install apr --universal" re-install apr and apr-util,then "brew install --universal --with-java subversion" works to success.

**Comment by DomT4** [comment]
Interesting. If anyone else encounters the error, we may need to try and work out why the subversion install pops these errors up unless the deps are installed first separately, but I'm glad we've managed to solve this for you :smiley:.

**Comment by barryhippo** [comment]
I'm very very glad to solve this error with your help.😄thanks very much.
