### ISSUE TITLE
How can evince open djvu files?

### ISSUE THREAD

**Issue by mistguy** [Homebrew/homebrew#48440]
I installed homebrew and evince in a vanilla El Caption macbook. However, I cannot open djvu files with evince(I have installed djvulibre inside homebrew). What else should I install to open files with evince?

**Comment by DomT4** [comment]
CC @tschoonj :smile_cat:

**Comment by tschoonj** [comment]
Fixed in #48471

**Comment by mistguy** [comment]
By the way, I wonder how to use evince as the default pdf and djvu viewer in El Caption. That is, evince is invoked by double click on a pdf or djvu file.

**Comment by tschoonj** [comment]
Impossible I'm afraid. Evince would need to be packaged into an app bundle for that plus it would need additional code to handle opening files from finder etc

**Comment by mistguy** [comment]
still cannot open djvu, the message is "File type DjVu document (image/vnd.djvu+multipage) is not supported"

**Comment by bfontaine** [comment]
@mistguy Just to be sure, did you run `brew update` and `brew upgrade evince`?

**Comment by mistguy** [comment]
yeah, I even tried to run `brew rmtree evince` and `brew install --build-from-source evince`.

**Comment by mistguy** [comment]
Update: I can open djvu with English names, but not those whose names contains Chinese characters

**Comment by tschoonj** [comment]
Fixed in #48506
